# Generated by Django 4.2 on 2023-04-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
        migrations.AlterField(
            model_name='destination',
            name='offer',
            field=models.BooleanField(),
        ),
    ]
